In [1]:
import pandas as pd 
import sqlite3

In [2]:
df = pd.read_csv("../data/superstore_clean.csv")
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin,Profit Status,Sales Category,Sales Outlier,Profit Outlier,Quantity Outlier
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,Profit,Medium,No,No,No
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,Profit,High,Yes,Yes,No
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,Profit,Low,No,No,No
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,Loss,High,Yes,Yes,No
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,Profit,Low,No,No,No

In [3]:
conn = sqlite3.connect('../data/superstore.db')

In [4]:
df.to_sql('orders', conn, if_exists='replace',index=False)

9977

In [6]:
pd.read_sql('SELECT * FROM orders LIMIT 5', conn)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin,Profit Status,Sales Category,Sales Outlier,Profit Outlier,Quantity Outlier
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00,Profit,Medium,No,No,No
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00,Profit,High,Yes,Yes,No
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00,Profit,Low,No,No,No
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00,Loss,High,Yes,Yes,No
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25,Profit,Low,No,No,No

In [9]:
with open('../sql/top10_products.sql','r') as file:
    query = file.read()
print(query)

SELECT
    "Sub-Category",
    SUM(Sales) AS revenue,
    SUM(Profit) AS profit
FROM orders
GROUP BY "Sub-Category"
ORDER BY revenue DESC
LIMIT 10;

In [10]:
result = pd.read_sql(query, conn)
result

  Sub-Category      revenue      profit
0       Phones  330007.0540  44515.7306
1       Chairs  327777.7610  26567.1278
2      Storage  223843.6080  21278.8264
3       Tables  206965.5320 -17725.4811
4      Binders  203409.1690  30228.0003
5     Machines  189238.6310   3384.7569
6  Accessories  167380.3180  41936.6357
7      Copiers  149528.0300  55617.8249
8    Bookcases  114879.9963  -3472.5560
9   Appliances  107532.1610  18138.0054

In [11]:
with open('../sql/region_performance.sql','r') as file:
    query = file.read()
print(query)

SELECT Region,
    SUM(Sales) AS total_sales,
    sUM(Profit) AS total_profit,
    ROUND(
        SUM(Profit) * 100.0/SUM(Sales),
        2
    ) AS profit_margin
FROM orders
GROUP BY Region;

In [12]:
result = pd.read_sql(query, conn)
result

    Region  total_sales  total_profit  profit_margin
0  Central  500782.8528    39655.8752           7.92
1     East  678435.1960    91506.3092          13.49
2    South  391721.9050    46749.4303          11.93
3     West  725255.6365   108329.8079          14.94

In [13]:
with open('../sql/category_breakdown.sql','r') as file:
    query = file.read()
print(query)

SELECT Category,
    SUM(Sales) AS sales,
    SUM(Profit) AS profit
FROM orders
GROUP BY Category
ORDER BY profit ASC;

In [14]:
result = pd.read_sql(query, conn)
result

          Category        sales       profit
0        Furniture  741306.3133   18421.8137
1  Office Supplies  718735.2440  122364.6608
2       Technology  836154.0330  145454.9481

In [15]:
with open('../sql/discount_impact.sql','r') as file:
    query = file.read()
print(query)

SELECT Discount,
    ROUND(AVG(Profit),2) AS avg_profit,
    ROUND(SUM(Sales),2) AS total_sales
FROM orders
GROUP BY Discount
ORDER BY Discount;

In [16]:
result = pd.read_sql(query, conn)
result

    Discount  avg_profit  total_sales
0       0.00       67.02   1087277.56
1       0.10       96.06     54369.35
2       0.15       27.29     27558.52
3       0.20       24.72    764504.94
4       0.30      -45.83    102945.28
5       0.32      -88.56     14493.46
6       0.40     -111.93    116417.78
7       0.45     -226.65      5484.97
8       0.50     -310.70     58918.54
9       0.60      -43.08      6644.70
10      0.70      -95.87     40620.28
11      0.80     -102.12     16960.19

In [19]:
with open('../sql/customer_segments.sql','r') as file:
    query = file.read()
print(query)

SELECT
    Segment,
    ROUND(SUM(Sales),2) AS revenue,
    ROUND(SUM(Profit),2) AS profit
FROM orders
GROUP BY Segment
ORDER BY revenue DESC;

In [20]:
result = pd.read_sql(query, conn)
result

       Segment     revenue     profit
0     Consumer  1160832.77  134007.44
1    Corporate   706070.13   91954.98
2  Home Office   429292.68   60279.00